/**
 * Integration Executive Trust Mock Data
 */

import { subHours, subDays, subMinutes, addDays } from 'date-fns';
import type {
  IntegrationSource,
  IntegrationStats,
  DataQualityRule,
  DataReadinessScore,
  AuditLogEntry,
} from './types';

export const MOCK_INTEGRATIONS: IntegrationSource[] = [
  {
    id: 'int-hris',
    name: 'HRIS System (SAP SuccessFactors)',
    description: 'Employee master data, org structure, employment history',
    icon: 'users',
    category: 'hris',
    status: 'healthy',
    lastSyncAt: subMinutes(new Date(), 15),
    nextSyncAt: addDays(new Date(), 0.0417), // ~1 hour
    syncFrequency: 'hourly',
    coverage: 98,
    recordsTotal: 12847,
    recordsSynced: 12590,
    recordsFailed: 23,
    dataFreshness: 'current',
    poweredDashboards: [
      {
        dashboardId: 'dash-exec',
        dashboardName: 'Executive Dashboard',
        dashboardPath: '/employer',
        dataFields: ['Employee Count', 'Headcount Trend', 'Department Distribution'],
        confidenceImpact: 'critical',
        lastDataUpdate: subMinutes(new Date(), 15),
      },
      {
        dashboardId: 'dash-spend',
        dashboardName: 'Spend & Forecast',
        dashboardPath: '/employer/spend',
        dataFields: ['Per-Employee Cost', 'Department Allocation'],
        confidenceImpact: 'high',
        lastDataUpdate: subMinutes(new Date(), 15),
      },
      {
        dashboardId: 'dash-segments',
        dashboardName: 'Drivers & Segments',
        dashboardPath: '/employer/segments',
        dataFields: ['Grade Distribution', 'Tenure Bands', 'Location Breakdown'],
        confidenceImpact: 'critical',
        lastDataUpdate: subMinutes(new Date(), 15),
      },
    ],
    issues: [],
  },
  {
    id: 'int-payroll',
    name: 'Payroll Provider (WPS)',
    description: 'Salary data, compensation, deductions, allowances',
    icon: 'banknote',
    category: 'payroll',
    status: 'healthy',
    lastSyncAt: subHours(new Date(), 6),
    nextSyncAt: addDays(new Date(), 1),
    syncFrequency: 'daily',
    coverage: 100,
    recordsTotal: 12650,
    recordsSynced: 12650,
    recordsFailed: 0,
    dataFreshness: 'current',
    poweredDashboards: [
      {
        dashboardId: 'dash-spend',
        dashboardName: 'Spend & Forecast',
        dashboardPath: '/employer/spend',
        dataFields: ['Total Compensation', 'Benefits Cost', 'YoY Trend'],
        confidenceImpact: 'critical',
        lastDataUpdate: subHours(new Date(), 6),
      },
      {
        dashboardId: 'dash-settlements',
        dashboardName: 'Settlements',
        dashboardPath: '/employer/settlements',
        dataFields: ['Payment Records', 'Reimbursements'],
        confidenceImpact: 'high',
        lastDataUpdate: subHours(new Date(), 6),
      },
    ],
    issues: [],
  },
  {
    id: 'int-claims',
    name: 'Claims Management System',
    description: 'Medical, education, and housing claims processing',
    icon: 'file-text',
    category: 'claims',
    status: 'degraded',
    lastSyncAt: subHours(new Date(), 2),
    nextSyncAt: addDays(new Date(), 0.0417),
    syncFrequency: 'hourly',
    coverage: 87,
    recordsTotal: 45200,
    recordsSynced: 39324,
    recordsFailed: 156,
    dataFreshness: 'stale',
    poweredDashboards: [
      {
        dashboardId: 'dash-ops',
        dashboardName: 'Operations Hub',
        dashboardPath: '/employer/ops',
        dataFields: ['Pending Claims', 'SLA Status', 'Processing Queue'],
        confidenceImpact: 'critical',
        lastDataUpdate: subHours(new Date(), 2),
      },
      {
        dashboardId: 'dash-spend',
        dashboardName: 'Spend & Forecast',
        dashboardPath: '/employer/spend',
        dataFields: ['Claims Spend', 'Utilization Rate'],
        confidenceImpact: 'high',
        lastDataUpdate: subHours(new Date(), 2),
      },
    ],
    issues: [
      {
        id: 'issue-1',
        type: 'sync',
        severity: 'warning',
        message: '156 records failed validation in last sync',
        detectedAt: subHours(new Date(), 2),
        fixAction: 'Review failed records',
        fixPath: '/employer/integrations?view=ops&tab=sync',
      },
      {
        id: 'issue-2',
        type: 'coverage',
        severity: 'warning',
        message: 'Coverage dropped below 90% threshold',
        detectedAt: subHours(new Date(), 2),
        fixAction: 'Map missing fields',
        fixPath: '/employer/integrations?view=ops&tab=mapping',
      },
    ],
  },
  {
    id: 'int-benefits',
    name: 'Benefits Platform',
    description: 'Insurance policies, wellness programs, perks enrollment',
    icon: 'heart',
    category: 'benefits',
    status: 'healthy',
    lastSyncAt: subHours(new Date(), 1),
    nextSyncAt: addDays(new Date(), 0.0417),
    syncFrequency: 'hourly',
    coverage: 95,
    recordsTotal: 11200,
    recordsSynced: 10640,
    recordsFailed: 0,
    dataFreshness: 'current',
    poweredDashboards: [
      {
        dashboardId: 'dash-exec',
        dashboardName: 'Executive Dashboard',
        dashboardPath: '/employer',
        dataFields: ['Utilization Rate', 'Satisfaction Score'],
        confidenceImpact: 'high',
        lastDataUpdate: subHours(new Date(), 1),
      },
      {
        dashboardId: 'dash-bench',
        dashboardName: 'Benchmarks',
        dashboardPath: '/employer/benchmarks',
        dataFields: ['Benefits Mix', 'Coverage Levels'],
        confidenceImpact: 'medium',
        lastDataUpdate: subHours(new Date(), 1),
      },
    ],
    issues: [],
  },
  {
    id: 'int-finance',
    name: 'Finance ERP (Oracle)',
    description: 'Budget allocations, cost centers, GL mapping',
    icon: 'landmark',
    category: 'finance',
    status: 'disconnected',
    lastSyncAt: subDays(new Date(), 7),
    nextSyncAt: null,
    syncFrequency: 'daily',
    coverage: 0,
    recordsTotal: 0,
    recordsSynced: 0,
    recordsFailed: 0,
    dataFreshness: 'very_stale',
    poweredDashboards: [
      {
        dashboardId: 'dash-spend',
        dashboardName: 'Spend & Forecast',
        dashboardPath: '/employer/spend',
        dataFields: ['Budget Allocation', 'Cost Center Mapping', 'GL Codes'],
        confidenceImpact: 'high',
        lastDataUpdate: subDays(new Date(), 7),
      },
    ],
    issues: [
      {
        id: 'issue-3',
        type: 'auth',
        severity: 'critical',
        message: 'Connection credentials expired',
        detectedAt: subDays(new Date(), 7),
        fixAction: 'Reconnect integration',
        fixPath: '/employer/integrations?view=ops',
      },
    ],
  },
];

export const MOCK_INTEGRATION_STATS: IntegrationStats = {
  totalSources: 5,
  connectedSources: 4,
  healthySources: 3,
  degradedSources: 1,
  overallCoverage: 76,
  dataReadinessScore: 82,
  lastGlobalSync: subMinutes(new Date(), 15),
  pendingIssues: 3,
};

export const MOCK_DATA_READINESS: DataReadinessScore = {
  overall: 82,
  completeness: 88,
  accuracy: 91,
  timeliness: 74,
  consistency: 85,
  trend: 'improving',
  lastUpdated: new Date(),
};

export const MOCK_DATA_QUALITY_RULES: DataQualityRule[] = [
  {
    id: 'rule-1',
    name: 'Employee Grade Required',
    description: 'All active employees must have a grade assignment',
    category: 'completeness',
    severity: 'critical',
    dataSource: 'HRIS',
    status: 'failing',
    lastChecked: subMinutes(new Date(), 30),
    violationCount: 47,
    affectedRecords: 47,
    impactedKPIs: [
      {
        kpiId: 'kpi-cost-per-head',
        kpiName: 'Cost per Employee by Grade',
        impactLevel: 'blocking',
        confidenceReduction: 15,
        dashboardPath: '/employer/spend',
      },
      {
        kpiId: 'kpi-segment',
        kpiName: 'Grade Distribution Analysis',
        impactLevel: 'degraded',
        confidenceReduction: 8,
        dashboardPath: '/employer/segments',
      },
    ],
    fixGuidance: 'Navigate to Employee Directory > Filter by "Missing Grade" > Update grade assignments via HRIS sync or manual entry.',
    autoFixAvailable: false,
  },
  {
    id: 'rule-2',
    name: 'Claim Amount Validation',
    description: 'Claims must have valid amounts within policy limits',
    category: 'validity',
    severity: 'high',
    dataSource: 'Claims',
    status: 'failing',
    lastChecked: subMinutes(new Date(), 15),
    violationCount: 23,
    affectedRecords: 23,
    impactedKPIs: [
      {
        kpiId: 'kpi-utilization',
        kpiName: 'Benefit Utilization Rate',
        impactLevel: 'degraded',
        confidenceReduction: 5,
        dashboardPath: '/employer/spend',
      },
    ],
    fixGuidance: 'Review flagged claims in Operations Hub > Claims Queue. Validate amounts against policy caps and request corrections.',
    autoFixAvailable: false,
  },
  {
    id: 'rule-3',
    name: 'Department Code Consistency',
    description: 'Department codes must match between HRIS and Payroll',
    category: 'consistency',
    severity: 'high',
    dataSource: 'HRIS, Payroll',
    status: 'failing',
    lastChecked: subMinutes(new Date(), 45),
    violationCount: 156,
    affectedRecords: 89,
    impactedKPIs: [
      {
        kpiId: 'kpi-dept-spend',
        kpiName: 'Department Spend Breakdown',
        impactLevel: 'blocking',
        confidenceReduction: 12,
        dashboardPath: '/employer/segments',
      },
      {
        kpiId: 'kpi-budget-track',
        kpiName: 'Budget vs Actual by Cost Center',
        impactLevel: 'degraded',
        confidenceReduction: 8,
        dashboardPath: '/employer/spend',
      },
    ],
    fixGuidance: 'Access Integrations > Field Mapping. Align department code mappings between HRIS and Payroll sources. Run validation after mapping.',
    autoFixAvailable: true,
  },
  {
    id: 'rule-4',
    name: 'Payroll Data Freshness',
    description: 'Payroll data must be updated within last 48 hours',
    category: 'timeliness',
    severity: 'medium',
    dataSource: 'Payroll',
    status: 'passing',
    lastChecked: subMinutes(new Date(), 10),
    violationCount: 0,
    affectedRecords: 0,
    impactedKPIs: [
      {
        kpiId: 'kpi-comp',
        kpiName: 'Total Compensation Cost',
        impactLevel: 'minor',
        confidenceReduction: 3,
        dashboardPath: '/employer/spend',
      },
    ],
    fixGuidance: 'Trigger manual sync from Integrations page or contact Payroll provider to restore automated sync.',
    autoFixAvailable: true,
  },
  {
    id: 'rule-5',
    name: 'Hire Date Format',
    description: 'All hire dates must be in valid ISO format',
    category: 'accuracy',
    severity: 'low',
    dataSource: 'HRIS',
    status: 'failing',
    lastChecked: subMinutes(new Date(), 20),
    violationCount: 12,
    affectedRecords: 12,
    impactedKPIs: [
      {
        kpiId: 'kpi-tenure',
        kpiName: 'Tenure Analysis',
        impactLevel: 'minor',
        confidenceReduction: 2,
        dashboardPath: '/employer/segments',
      },
    ],
    fixGuidance: 'Review CSV import or HRIS field mapping. Update date format transformation rule in Integration Settings.',
    autoFixAvailable: true,
  },
  {
    id: 'rule-6',
    name: 'Email Uniqueness',
    description: 'Employee emails must be unique across records',
    category: 'accuracy',
    severity: 'medium',
    dataSource: 'HRIS',
    status: 'passing',
    lastChecked: subMinutes(new Date(), 60),
    violationCount: 0,
    affectedRecords: 0,
    impactedKPIs: [],
    fixGuidance: 'Identify and merge duplicate employee records in HRIS.',
    autoFixAvailable: false,
  },
  {
    id: 'rule-7',
    name: 'Benefit Enrollment Active',
    description: 'Active employees must have current benefit enrollments',
    category: 'completeness',
    severity: 'high',
    dataSource: 'Benefits',
    status: 'warning',
    lastChecked: subMinutes(new Date(), 25),
    violationCount: 34,
    affectedRecords: 34,
    impactedKPIs: [
      {
        kpiId: 'kpi-coverage',
        kpiName: 'Benefits Coverage Rate',
        impactLevel: 'degraded',
        confidenceReduction: 6,
        dashboardPath: '/employer',
      },
    ],
    fixGuidance: 'Review employees without enrollments in Employee Directory. Trigger enrollment reminders or manual assignments.',
    autoFixAvailable: false,
  },
];

export const MOCK_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'log-1',
    timestamp: subMinutes(new Date(), 5),
    actor: { userId: 'u-1', name: 'Sarah Ahmed', role: 'HR Operations', email: 'sarah.ahmed@company.com' },
    action: 'approve',
    resource: { type: 'claim', id: 'clm-892', name: 'Claim #CLM-2024-0892' },
    outcome: 'success',
    details: 'Approved medical claim for AED 2,500',
    isPIIAccess: false,
  },
  {
    id: 'log-2',
    timestamp: subMinutes(new Date(), 12),
    actor: { userId: 'u-2', name: 'Mohammed Al-Rashid', role: 'HR Director', email: 'mohammed.r@company.com' },
    action: 'pii_access',
    resource: { type: 'employee', id: 'emp-456', name: 'Ahmed Khalil' },
    outcome: 'success',
    details: 'Accessed salary and Emirates ID for claims processing',
    isPIIAccess: true,
    piiFields: ['monthly_salary', 'emirates_id'],
    metadata: { reason: 'Claims verification', approved_by: 'system' },
  },
  {
    id: 'log-3',
    timestamp: subMinutes(new Date(), 45),
    actor: { userId: 'system', name: 'System', role: 'Automated' },
    action: 'sync',
    resource: { type: 'integration', id: 'int-hris', name: 'HRIS System' },
    outcome: 'success',
    details: 'Synced 12,847 employee records',
    isPIIAccess: false,
  },
  {
    id: 'log-4',
    timestamp: subHours(new Date(), 2),
    actor: { userId: 'u-3', name: 'Fatima Khan', role: 'Claims Processor', email: 'fatima.k@company.com' },
    action: 'reject',
    resource: { type: 'claim', id: 'clm-890', name: 'Claim #CLM-2024-0890' },
    outcome: 'success',
    details: 'Rejected claim: Missing required documentation',
    isPIIAccess: false,
  },
  {
    id: 'log-5',
    timestamp: subHours(new Date(), 3),
    actor: { userId: 'u-4', name: 'Ali Hassan', role: 'HR Analyst', email: 'ali.h@company.com' },
    action: 'export',
    resource: { type: 'report', id: 'rpt-q4', name: 'Q4 Spend Report' },
    outcome: 'success',
    details: 'Exported spend analysis report (PDF, 24 pages)',
    isPIIAccess: false,
  },
  {
    id: 'log-6',
    timestamp: subHours(new Date(), 4),
    actor: { userId: 'u-1', name: 'Sarah Ahmed', role: 'HR Operations', email: 'sarah.ahmed@company.com' },
    action: 'pii_access',
    resource: { type: 'employee', id: 'emp-789', name: 'Layla Omar' },
    outcome: 'success',
    details: 'Accessed passport number for visa processing',
    isPIIAccess: true,
    piiFields: ['passport_number', 'emirates_id'],
    metadata: { reason: 'Visa renewal documentation' },
  },
  {
    id: 'log-7',
    timestamp: subHours(new Date(), 6),
    actor: { userId: 'u-5', name: 'Khalid Ibrahim', role: 'Finance Manager', email: 'khalid.i@company.com' },
    action: 'update',
    resource: { type: 'budget', id: 'bgt-2024', name: 'FY2024 Benefits Budget' },
    outcome: 'success',
    details: 'Updated Q4 allocation: +AED 150,000 to Education',
    isPIIAccess: false,
  },
  {
    id: 'log-8',
    timestamp: subDays(new Date(), 1),
    actor: { userId: 'u-2', name: 'Mohammed Al-Rashid', role: 'HR Director', email: 'mohammed.r@company.com' },
    action: 'permission_change',
    resource: { type: 'user', id: 'u-6', name: 'Nadia Salem' },
    outcome: 'success',
    details: 'Granted claims processing permission',
    isPIIAccess: false,
    metadata: { previous: 'read_only', new: 'claims_processor' },
  },
  {
    id: 'log-9',
    timestamp: subDays(new Date(), 1),
    actor: { userId: 'u-7', name: 'Omar Faisal', role: 'IT Admin', email: 'omar.f@company.com' },
    action: 'config_change',
    resource: { type: 'integration', id: 'int-claims', name: 'Claims System' },
    outcome: 'success',
    details: 'Updated API endpoint configuration',
    isPIIAccess: false,
  },
  {
    id: 'log-10',
    timestamp: subDays(new Date(), 2),
    actor: { userId: 'u-8', name: 'Aisha Mahmoud', role: 'Unknown', email: 'aisha.m@company.com' },
    action: 'pii_access',
    resource: { type: 'sensitive_data', id: 'bulk-export', name: 'Employee Salary Export' },
    outcome: 'failure',
    details: 'Bulk PII access denied: Insufficient permissions',
    isPIIAccess: true,
    piiFields: ['monthly_salary'],
    metadata: { blocked_reason: 'Missing export_pii permission' },
  },
];
