import { 
  Users, 
  Building2, 
  DollarSign, 
  Heart, 
  Calendar,
  Briefcase,
  GraduationCap,
  Shield,
  Store,
  ShoppingBag,
  Stethoscope,
  Home,
  Car,
  Plane,
  Gift,
  Settings,
  CreditCard,
  FileText,
  Award,
} from 'lucide-react';

export interface FieldSpec {
  name: string;
  type: string;
  required: boolean;
  description: string;
  example: string;
  validation?: string;
}

export interface TemplateSection {
  id: string;
  title: string;
  description: string;
  icon: React.ElementType;
  tableName: string;
  fields: FieldSpec[];
  notes?: string[];
  category: 'organization' | 'employees' | 'compensation' | 'benefits' | 'leave' | 'vendors' | 'marketplace' | 'reference';
}

// Organization Setup
export const organizationSetupTemplate: TemplateSection = {
  id: 'organization_setup',
  title: 'Organization Configuration',
  description: 'Company-level settings, branding, and system configuration',
  icon: Building2,
  tableName: 'organizations',
  category: 'organization',
  fields: [
    { name: 'organization_name', type: 'String', required: true, description: 'Legal company name', example: 'Demo Company LLC', validation: 'Max 200 characters' },
    { name: 'organization_name_ar', type: 'String', required: false, description: 'Arabic company name', example: 'شركة ديمو ذ.م.م', validation: 'Arabic text' },
    { name: 'domain', type: 'String', required: true, description: 'Email domain for SSO', example: 'company.com', validation: 'Valid domain' },
    { name: 'logo_url', type: 'URL', required: false, description: 'Company logo URL', example: 'https://cdn.company.com/logo.png', validation: 'Valid URL, PNG/SVG' },
    { name: 'primary_color', type: 'String', required: false, description: 'Brand primary color', example: '#0f766e', validation: 'Hex color code' },
    { name: 'secondary_color', type: 'String', required: false, description: 'Brand secondary color', example: '#115e59', validation: 'Hex color code' },
    { name: 'accent_color', type: 'String', required: false, description: 'Brand accent color', example: '#2dd4bf', validation: 'Hex color code' },
    { name: 'fiscal_year_start', type: 'String', required: true, description: 'Fiscal year start month', example: '01', validation: '01-12' },
    { name: 'default_currency', type: 'String', required: true, description: 'Default currency', example: 'AED', validation: 'ISO currency code' },
    { name: 'timezone', type: 'String', required: true, description: 'Organization timezone', example: 'Asia/Dubai', validation: 'IANA timezone' },
    { name: 'welcome_message', type: 'Text', required: false, description: 'Dashboard welcome text', example: 'Welcome to your benefits portal', validation: 'Max 500 chars' },
    { name: 'footer_text', type: 'String', required: false, description: 'Footer copyright text', example: '© 2026 Company LLC', validation: 'Max 200 chars' },
    { name: 'industry', type: 'String', required: true, description: 'Industry sector', example: 'Technology', validation: 'Standard industry names' },
    { name: 'company_size', type: 'Enum', required: true, description: 'Company size bracket', example: '201-500', validation: '1-50, 51-200, 201-500, 501-1000, 1000+' },
    { name: 'head_office_address', type: 'Text', required: false, description: 'Head office address', example: 'DIFC Gate Building, Dubai', validation: 'Max 300 chars' },
    { name: 'hr_contact_email', type: 'Email', required: true, description: 'HR department email', example: 'hr@company.com', validation: 'Valid email' },
    { name: 'hr_contact_phone', type: 'String', required: false, description: 'HR contact number', example: '+971 4 123 4567', validation: 'International format' },
  ],
  notes: [
    'Domain is used for automatic user provisioning via SSO',
    'Colors should meet WCAG contrast requirements',
    'Fiscal year affects benefit period calculations',
    'Industry and company size used for benchmarking',
  ],
};

// Employee Master Data
export const employeeDataTemplate: TemplateSection = {
  id: 'employee_data',
  title: 'Employee Master Data',
  description: 'Core employee information required for user profiles and benefits assignment',
  icon: Users,
  tableName: 'profiles',
  category: 'employees',
  fields: [
    { name: 'employee_id', type: 'String', required: true, description: 'Unique employee identifier from HR system', example: 'EMP-001234', validation: 'Must be unique across organization' },
    { name: 'email', type: 'Email', required: true, description: 'Corporate email address (used for login)', example: 'john.smith@company.com', validation: 'Valid email format' },
    { name: 'first_name', type: 'String', required: true, description: 'Employee first name', example: 'John', validation: 'Max 50 characters' },
    { name: 'last_name', type: 'String', required: true, description: 'Employee last name', example: 'Smith', validation: 'Max 50 characters' },
    { name: 'phone', type: 'String', required: false, description: 'Mobile phone number with country code', example: '+971501234567', validation: 'International format' },
    { name: 'nationality', type: 'String', required: true, description: 'Country of citizenship', example: 'United Kingdom', validation: 'ISO country name' },
    { name: 'date_of_birth', type: 'Date', required: true, description: 'Birth date for age-related benefits', example: '1985-06-15', validation: 'YYYY-MM-DD format' },
    { name: 'emirates_id', type: 'String', required: true, description: 'UAE Emirates ID number', example: '784-1985-1234567-1', validation: '15 digits with hyphens' },
    { name: 'passport_number', type: 'String', required: true, description: 'Passport number', example: 'AB1234567', validation: 'Alphanumeric' },
    { name: 'passport_expiry', type: 'Date', required: true, description: 'Passport expiry date', example: '2028-06-15', validation: 'YYYY-MM-DD, must be future' },
    { name: 'blood_type', type: 'Enum', required: false, description: 'Blood type for medical emergencies', example: 'O+', validation: 'A+, A-, B+, B-, AB+, AB-, O+, O-' },
    { name: 'marital_status', type: 'Enum', required: true, description: 'Marital status (affects family benefits)', example: 'Married', validation: 'Single, Married, Divorced, Widowed' },
    { name: 'spouse_name', type: 'String', required: false, description: 'Spouse name if married', example: 'Jane Smith', validation: 'Required if married' },
    { name: 'spouse_employer', type: 'String', required: false, description: 'Spouse employer (for duplicate benefit check)', example: 'ABC Corporation', validation: 'Optional' },
    { name: 'spouse_working', type: 'Boolean', required: false, description: 'Is spouse employed', example: 'true', validation: 'true/false' },
    { name: 'number_of_dependents', type: 'Integer', required: false, description: 'Total number of dependents', example: '3', validation: 'Positive integer' },
    { name: 'emergency_contact_name', type: 'String', required: true, description: 'Emergency contact full name', example: 'Mary Smith', validation: 'Max 100 characters' },
    { name: 'emergency_contact_phone', type: 'String', required: true, description: 'Emergency contact phone', example: '+971501234568', validation: 'International format' },
    { name: 'emergency_contact_relation', type: 'String', required: true, description: 'Relationship to emergency contact', example: 'Spouse', validation: 'e.g., Spouse, Parent, Sibling' },
    { name: 'home_location', type: 'String', required: false, description: 'Residential area for transport calculation', example: 'Dubai Marina', validation: 'Free text' },
    { name: 'home_address', type: 'Text', required: false, description: 'Full residential address', example: 'Apt 2301, Marina Heights, Dubai Marina', validation: 'Max 300 chars' },
    { name: 'preferred_language', type: 'Enum', required: false, description: 'UI language preference', example: 'en', validation: 'en, ar' },
    { name: 'avatar_url', type: 'URL', required: false, description: 'Profile photo URL', example: 'https://cdn.company.com/avatars/john.jpg', validation: 'Valid URL' },
    { name: 'interests', type: 'Array', required: false, description: 'Personal interests (comma-separated)', example: 'Sports, Reading, Travel', validation: 'Comma-separated values' },
    { name: 'pets', type: 'Array', required: false, description: 'Pets owned (comma-separated)', example: 'Dog, Cat', validation: 'Comma-separated values' },
    { name: 'cars', type: 'Array', required: false, description: 'Vehicles owned (comma-separated)', example: 'Toyota Camry 2023, Honda CR-V 2022', validation: 'Comma-separated values' },
  ],
  notes: [
    'All personal data is encrypted at rest and in transit',
    'Emirates ID and Passport are stored in encrypted format',
    'Marital status determines eligibility for family benefits',
    'Home location is used for transport allowance and commute calculations',
    'Interests and pets help personalize marketplace recommendations',
  ],
};

// Employment Details
export const employmentDataTemplate: TemplateSection = {
  id: 'employment_data',
  title: 'Employment Details',
  description: 'Job-related information for organizational structure and benefit tiers',
  icon: Briefcase,
  tableName: 'profiles',
  category: 'employees',
  fields: [
    { name: 'employee_id', type: 'String', required: true, description: 'Employee ID (links to master data)', example: 'EMP-001234', validation: 'Must exist in employee data' },
    { name: 'employment_date', type: 'Date', required: true, description: 'Date of joining the organization', example: '2023-01-15', validation: 'YYYY-MM-DD format' },
    { name: 'department', type: 'String', required: true, description: 'Department name', example: 'Technology', validation: 'Must match org structure' },
    { name: 'division', type: 'String', required: false, description: 'Division within department', example: 'Product Engineering', validation: 'Must match org structure' },
    { name: 'cost_center', type: 'String', required: false, description: 'Cost center code', example: 'CC-TECH-001', validation: 'Alphanumeric' },
    { name: 'position', type: 'String', required: true, description: 'Job title', example: 'Senior Product Manager', validation: 'Max 100 characters' },
    { name: 'job_family', type: 'String', required: false, description: 'Job family classification', example: 'Product Management', validation: 'Standard job families' },
    { name: 'grade', type: 'String', required: true, description: 'Employee grade/level for benefit tiers', example: 'G7', validation: 'Must match grade structure' },
    { name: 'band', type: 'String', required: false, description: 'Salary band', example: 'Band C', validation: 'Must match band structure' },
    { name: 'work_location', type: 'String', required: true, description: 'Office location', example: 'DIFC Tower 2', validation: 'Must match location list' },
    { name: 'work_country', type: 'String', required: true, description: 'Work country', example: 'United Arab Emirates', validation: 'ISO country name' },
    { name: 'manager_name', type: 'String', required: false, description: 'Direct manager name', example: 'Sarah Johnson', validation: 'Max 100 characters' },
    { name: 'manager_email', type: 'Email', required: false, description: 'Manager email for approvals', example: 'sarah.johnson@company.com', validation: 'Valid email' },
    { name: 'manager_employee_id', type: 'String', required: false, description: 'Manager employee ID', example: 'EMP-000987', validation: 'Must exist in employees' },
    { name: 'contract_type', type: 'Enum', required: true, description: 'Employment contract type', example: 'Permanent', validation: 'Permanent, Fixed-term, Probation, Contractor' },
    { name: 'contract_end_date', type: 'Date', required: false, description: 'Contract end date (for fixed-term)', example: '2025-12-31', validation: 'YYYY-MM-DD format' },
    { name: 'probation_end_date', type: 'Date', required: false, description: 'Probation period end date', example: '2023-04-15', validation: 'YYYY-MM-DD format' },
    { name: 'employment_status', type: 'Enum', required: true, description: 'Current employment status', example: 'Active', validation: 'Active, On Leave, Suspended, Terminated' },
    { name: 'termination_date', type: 'Date', required: false, description: 'Last working day if terminated', example: '2025-03-31', validation: 'YYYY-MM-DD format' },
    { name: 'notice_period_days', type: 'Integer', required: false, description: 'Notice period in days', example: '30', validation: 'Positive integer' },
    { name: 'visa_type', type: 'String', required: true, description: 'Work visa type', example: 'Employment Visa', validation: 'Employment, Investor, Freelancer, etc.' },
    { name: 'visa_expiry', type: 'Date', required: true, description: 'Visa expiry date', example: '2025-12-31', validation: 'YYYY-MM-DD format' },
    { name: 'labor_card_number', type: 'String', required: false, description: 'UAE labor card number', example: 'LC123456789', validation: 'Alphanumeric' },
  ],
  notes: [
    'Grade determines benefit tier and allowance amounts',
    'Department is used for segment analytics and reporting',
    'Manager email enables approval workflows',
    'Visa expiry dates trigger automatic renewal notifications',
    'Cost center used for benefit expense allocation',
  ],
};

// Salary & Compensation
export const salaryDataTemplate: TemplateSection = {
  id: 'salary_data',
  title: 'Salary & Compensation',
  description: 'Compensation data for salary display and benefit calculations',
  icon: DollarSign,
  tableName: 'profiles',
  category: 'compensation',
  fields: [
    { name: 'employee_id', type: 'String', required: true, description: 'Employee ID (links to master data)', example: 'EMP-001234', validation: 'Must exist in employee data' },
    { name: 'monthly_basic_salary', type: 'Decimal', required: true, description: 'Monthly basic salary', example: '25000.00', validation: 'Positive number' },
    { name: 'housing_allowance_monthly', type: 'Decimal', required: true, description: 'Monthly housing allowance', example: '10000.00', validation: 'Positive number' },
    { name: 'transport_allowance_monthly', type: 'Decimal', required: true, description: 'Monthly transport allowance', example: '2000.00', validation: 'Positive number' },
    { name: 'education_allowance_monthly', type: 'Decimal', required: false, description: 'Monthly education allowance', example: '3000.00', validation: 'Positive number' },
    { name: 'mobile_allowance_monthly', type: 'Decimal', required: false, description: 'Monthly mobile/phone allowance', example: '500.00', validation: 'Positive number' },
    { name: 'meal_allowance_monthly', type: 'Decimal', required: false, description: 'Monthly meal allowance', example: '1000.00', validation: 'Positive number' },
    { name: 'other_allowances_monthly', type: 'Decimal', required: false, description: 'Other monthly allowances', example: '1500.00', validation: 'Positive number' },
    { name: 'annual_bonus_target_percent', type: 'Decimal', required: false, description: 'Target annual bonus (% of base)', example: '20', validation: '0-200' },
    { name: 'annual_bonus_actual', type: 'Decimal', required: false, description: 'Actual annual bonus amount', example: '60000.00', validation: 'Positive number' },
    { name: 'equity_grant_value', type: 'Decimal', required: false, description: 'Total equity grant value', example: '100000.00', validation: 'Positive number' },
    { name: 'equity_vested', type: 'Decimal', required: false, description: 'Vested equity value', example: '25000.00', validation: 'Positive number' },
    { name: 'equity_unvested', type: 'Decimal', required: false, description: 'Unvested equity value', example: '75000.00', validation: 'Positive number' },
    { name: 'currency', type: 'String', required: true, description: 'Salary currency code', example: 'AED', validation: 'ISO currency code' },
    { name: 'payment_frequency', type: 'Enum', required: true, description: 'Salary payment frequency', example: 'Monthly', validation: 'Monthly, Bi-weekly, Weekly' },
    { name: 'bank_name', type: 'String', required: false, description: 'Salary bank name', example: 'Emirates NBD', validation: 'Free text' },
    { name: 'bank_account_iban', type: 'String', required: false, description: 'Bank account IBAN', example: 'AE070331234567890123456', validation: 'Valid IBAN format' },
    { name: 'effective_date', type: 'Date', required: true, description: 'Salary effective date', example: '2024-01-01', validation: 'YYYY-MM-DD format' },
    { name: 'next_review_date', type: 'Date', required: false, description: 'Next salary review date', example: '2025-01-01', validation: 'YYYY-MM-DD format' },
    { name: 'gratuity_eligible', type: 'Boolean', required: true, description: 'Eligible for end of service gratuity', example: 'true', validation: 'true/false' },
    { name: 'pension_contribution_percent', type: 'Decimal', required: false, description: 'Pension contribution percentage', example: '5', validation: '0-100' },
  ],
  notes: [
    'Salary data is encrypted and only visible to authorized users',
    'Housing allowance affects eligibility for housing benefit programs',
    'Annual bonus target is used for total compensation display',
    'Equity values should be updated quarterly',
    'Gratuity calculated based on UAE Labor Law requirements',
  ],
};

// Dependents & Family
export const dependentsDataTemplate: TemplateSection = {
  id: 'dependents_data',
  title: 'Dependents & Family',
  description: 'Family member data for education, health, and family benefits',
  icon: GraduationCap,
  tableName: 'children',
  category: 'employees',
  fields: [
    { name: 'employee_id', type: 'String', required: true, description: 'Parent employee ID', example: 'EMP-001234', validation: 'Must exist in employees' },
    { name: 'dependent_type', type: 'Enum', required: true, description: 'Relationship to employee', example: 'Child', validation: 'Spouse, Child, Parent, Sibling' },
    { name: 'name', type: 'String', required: true, description: 'Dependent full name', example: 'Emily Smith', validation: 'Max 100 characters' },
    { name: 'date_of_birth', type: 'Date', required: true, description: 'Dependent birth date', example: '2015-03-20', validation: 'YYYY-MM-DD format' },
    { name: 'gender', type: 'Enum', required: true, description: 'Dependent gender', example: 'Female', validation: 'Male, Female' },
    { name: 'nationality', type: 'String', required: false, description: 'Dependent nationality', example: 'United Kingdom', validation: 'ISO country name' },
    { name: 'emirates_id', type: 'String', required: false, description: 'Dependent Emirates ID', example: '784-2015-1234568-1', validation: '15 digits' },
    { name: 'passport_number', type: 'String', required: false, description: 'Dependent passport number', example: 'CD1234567', validation: 'Alphanumeric' },
    { name: 'visa_status', type: 'Enum', required: false, description: 'Dependent visa status', example: 'Sponsored', validation: 'Sponsored, Own Visa, Pending' },
    { name: 'visa_expiry', type: 'Date', required: false, description: 'Dependent visa expiry', example: '2025-12-31', validation: 'YYYY-MM-DD format' },
    { name: 'school_name', type: 'String', required: false, description: 'Current school name', example: 'GEMS Wellington Academy', validation: 'For school-age children' },
    { name: 'school_curriculum', type: 'String', required: false, description: 'School curriculum type', example: 'British', validation: 'British, American, IB, Indian, etc.' },
    { name: 'grade_level', type: 'String', required: false, description: 'Current school grade', example: 'Grade 5', validation: 'KG1-Grade 12' },
    { name: 'annual_tuition', type: 'Decimal', required: false, description: 'Annual school tuition', example: '55000.00', validation: 'Positive number' },
    { name: 'education_benefit_utilized', type: 'Decimal', required: false, description: 'Education benefit used this year', example: '45000.00', validation: 'Positive number' },
    { name: 'health_insurance_included', type: 'Boolean', required: true, description: 'Include in health insurance', example: 'true', validation: 'true/false' },
    { name: 'health_card_number', type: 'String', required: false, description: 'Health insurance card number', example: 'HC123456789', validation: 'Alphanumeric' },
    { name: 'special_needs', type: 'Boolean', required: false, description: 'Has special needs requiring accommodation', example: 'false', validation: 'true/false' },
    { name: 'special_needs_details', type: 'Text', required: false, description: 'Special needs description', example: 'Learning support required', validation: 'Max 500 chars' },
  ],
  notes: [
    'Children over 18 may not be eligible for education benefits (check policy)',
    'Spouse employment status affects duplicate benefit checks',
    'Health insurance coverage depends on policy tier and family size',
    'Special needs flag triggers additional support resources',
    'Education benefit is typically capped per child per academic year',
  ],
};

// Benefits Policy Structure
export const benefitsPolicyTemplate: TemplateSection = {
  id: 'benefits_policy',
  title: 'Benefits Policy Structure',
  description: 'Define benefit types, categories, and policy rules',
  icon: Heart,
  tableName: 'benefits',
  category: 'benefits',
  fields: [
    { name: 'benefit_code', type: 'String', required: true, description: 'Unique benefit identifier', example: 'HOUSING_ALLOW', validation: 'Uppercase, underscores only' },
    { name: 'benefit_name', type: 'String', required: true, description: 'Display name in English', example: 'Housing Allowance', validation: 'Max 100 characters' },
    { name: 'benefit_name_ar', type: 'String', required: true, description: 'Display name in Arabic', example: 'بدل السكن', validation: 'Arabic text' },
    { name: 'benefit_type', type: 'Enum', required: true, description: 'Benefit category type', example: 'cash_allowances', validation: 'cash_allowances, health_protection, time_off_flex, growth_career, wealth_ownership, wellbeing' },
    { name: 'life_area', type: 'Enum', required: true, description: 'Life area for dashboard grouping', example: 'home_living', validation: 'home_living, family_parenting, health, money, career, lifestyle, mobility' },
    { name: 'description', type: 'Text', required: true, description: 'Benefit description', example: 'Monthly housing support to help employees with accommodation costs in the UAE.', validation: 'Max 500 characters' },
    { name: 'description_ar', type: 'Text', required: false, description: 'Arabic description', example: 'دعم شهري للسكن لمساعدة الموظفين في تكاليف الإقامة', validation: 'Arabic text' },
    { name: 'icon', type: 'String', required: false, description: 'Icon name for display', example: 'Home', validation: 'Lucide icon name' },
    { name: 'policy_bullets', type: 'Array', required: false, description: 'Key policy points (pipe-separated)', example: 'Paid monthly|Tax-free|Subject to grade', validation: 'Pipe-separated values' },
    { name: 'is_taxable', type: 'Boolean', required: true, description: 'Subject to taxation', example: 'false', validation: 'true/false' },
    { name: 'is_active', type: 'Boolean', required: true, description: 'Benefit is currently active', example: 'true', validation: 'true/false' },
    { name: 'requires_approval', type: 'Boolean', required: true, description: 'Requires manager approval to claim', example: 'false', validation: 'true/false' },
    { name: 'requires_documentation', type: 'Boolean', required: true, description: 'Requires supporting documents', example: 'true', validation: 'true/false' },
    { name: 'document_types_accepted', type: 'Array', required: false, description: 'Accepted document types', example: 'Receipt|Invoice|Contract', validation: 'Pipe-separated values' },
    { name: 'claim_frequency', type: 'Enum', required: true, description: 'How often can be claimed', example: 'Monthly', validation: 'One-time, Monthly, Quarterly, Annual, As-needed' },
    { name: 'claim_deadline_days', type: 'Integer', required: false, description: 'Days after expense to submit claim', example: '30', validation: 'Positive integer' },
    { name: 'proration_rule', type: 'Enum', required: true, description: 'Proration for new joiners', example: 'Monthly', validation: 'None, Monthly, Quarterly' },
    { name: 'eligibility_criteria', type: 'Text', required: false, description: 'Eligibility requirements', example: 'All permanent employees after probation', validation: 'Max 500 chars' },
    { name: 'exclusions', type: 'Text', required: false, description: 'What is not covered', example: 'Contractors and temporary staff', validation: 'Max 500 chars' },
    { name: 'annual_value', type: 'Decimal', required: false, description: 'Default annual value', example: '120000.00', validation: 'Positive number' },
    { name: 'display_order', type: 'Integer', required: false, description: 'Display order in UI', example: '1', validation: 'Positive integer' },
  ],
  notes: [
    'Each benefit type maps to a life area for dashboard grouping',
    'Proration rules apply to mid-year joiners',
    'Approval workflows are configured based on amount thresholds',
    'Document requirements vary by benefit type',
    'Policy bullets appear in employee-facing descriptions',
  ],
};

// Benefit Entitlements by Grade
export const benefitEntitlementTemplate: TemplateSection = {
  id: 'benefit_entitlement',
  title: 'Benefit Entitlements by Grade',
  description: 'Map employee grades to specific benefit amounts and rules',
  icon: Shield,
  tableName: 'benefit_entitlements',
  category: 'benefits',
  fields: [
    { name: 'grade', type: 'String', required: true, description: 'Employee grade level', example: 'G7', validation: 'Must match grade structure' },
    { name: 'benefit_code', type: 'String', required: true, description: 'Benefit code', example: 'HOUSING_ALLOW', validation: 'Must exist in benefits' },
    { name: 'annual_allowance', type: 'Decimal', required: true, description: 'Annual entitlement amount', example: '120000.00', validation: 'Positive number' },
    { name: 'monthly_equivalent', type: 'Decimal', required: false, description: 'Monthly equivalent (calculated)', example: '10000.00', validation: 'Positive number' },
    { name: 'max_claim_per_transaction', type: 'Decimal', required: false, description: 'Max single claim amount', example: '10000.00', validation: 'Positive number' },
    { name: 'min_claim_amount', type: 'Decimal', required: false, description: 'Minimum claim amount', example: '100.00', validation: 'Positive number' },
    { name: 'rollover_allowed', type: 'Boolean', required: true, description: 'Unused balance rolls over', example: 'false', validation: 'true/false' },
    { name: 'rollover_max_percent', type: 'Decimal', required: false, description: 'Max % that can roll over', example: '25', validation: '0-100' },
    { name: 'rollover_expiry_months', type: 'Integer', required: false, description: 'Months until rollover expires', example: '3', validation: 'Positive integer' },
    { name: 'eligibility_start', type: 'Enum', required: true, description: 'When benefit becomes active', example: 'Immediately', validation: 'Immediately, After_Probation, After_6_Months, After_1_Year' },
    { name: 'dependent_coverage', type: 'Enum', required: false, description: 'Family coverage level', example: 'Employee_Spouse_Children', validation: 'Employee_Only, Employee_Spouse, Employee_Spouse_Children, Full_Family' },
    { name: 'dependent_max_count', type: 'Integer', required: false, description: 'Max dependents covered', example: '4', validation: 'Positive integer' },
    { name: 'waiting_period_days', type: 'Integer', required: false, description: 'Waiting period before eligible', example: '90', validation: 'Positive integer' },
    { name: 'coverage_percent', type: 'Decimal', required: false, description: 'Percentage of cost covered', example: '80', validation: '0-100' },
    { name: 'requires_co_pay', type: 'Boolean', required: false, description: 'Employee co-payment required', example: 'true', validation: 'true/false' },
    { name: 'co_pay_percent', type: 'Decimal', required: false, description: 'Employee co-pay percentage', example: '20', validation: '0-100' },
  ],
  notes: [
    'Grade-based entitlements override default benefit values',
    'Rollover rules are processed at fiscal year end',
    'Eligibility conditions are checked automatically at login',
    'Dependent coverage affects family benefit calculations',
    'Co-pay requirements apply to insurance and medical benefits',
  ],
};

// Leave Balances
export const leaveBalanceTemplate: TemplateSection = {
  id: 'leave_balance',
  title: 'Leave Balances & Policies',
  description: 'Initial leave balances and accrual configuration',
  icon: Calendar,
  tableName: 'leave_balances',
  category: 'leave',
  fields: [
    { name: 'employee_id', type: 'String', required: true, description: 'Employee ID', example: 'EMP-001234', validation: 'Must exist in employees' },
    { name: 'leave_type', type: 'Enum', required: true, description: 'Type of leave', example: 'Annual', validation: 'Annual, Sick, Maternity, Paternity, Compassionate, Hajj, Study, Unpaid' },
    { name: 'year', type: 'Integer', required: true, description: 'Leave year', example: '2026', validation: 'YYYY format' },
    { name: 'total_days', type: 'Integer', required: true, description: 'Total entitled days', example: '30', validation: 'Positive integer' },
    { name: 'used_days', type: 'Integer', required: true, description: 'Days already used', example: '5', validation: '0 or positive integer' },
    { name: 'pending_days', type: 'Integer', required: false, description: 'Days in pending requests', example: '3', validation: '0 or positive integer' },
    { name: 'carried_over', type: 'Integer', required: false, description: 'Days carried from previous year', example: '5', validation: '0 or positive integer' },
    { name: 'accrual_rate', type: 'Enum', required: true, description: 'How leave accrues', example: 'Monthly', validation: 'Upfront, Monthly, Quarterly' },
    { name: 'accrued_to_date', type: 'Decimal', required: false, description: 'Days accrued so far', example: '15.5', validation: 'Positive number' },
    { name: 'encashment_allowed', type: 'Boolean', required: true, description: 'Can encash unused leave', example: 'true', validation: 'true/false' },
    { name: 'max_encashment_days', type: 'Integer', required: false, description: 'Max days that can be encashed', example: '10', validation: 'Positive integer' },
    { name: 'encashment_rate', type: 'Decimal', required: false, description: 'Daily encashment rate', example: '850.00', validation: 'Positive number (basic salary / 30)' },
    { name: 'max_consecutive_days', type: 'Integer', required: false, description: 'Max consecutive days allowed', example: '20', validation: 'Positive integer' },
    { name: 'requires_approval', type: 'Boolean', required: true, description: 'Requires manager approval', example: 'true', validation: 'true/false' },
    { name: 'advance_notice_days', type: 'Integer', required: false, description: 'Days notice required', example: '7', validation: 'Positive integer' },
  ],
  notes: [
    'UAE Labor Law mandates minimum 30 days annual leave after 1 year',
    'Sick leave requires medical certificate after 2 consecutive days',
    'Maternity leave is 60 days (45 full pay, 15 half pay)',
    'Paternity leave is 5 working days (within 6 months of birth)',
    'Hajj leave is once during employment (30 days unpaid)',
  ],
};

// Vendor Data
export const vendorDataTemplate: TemplateSection = {
  id: 'vendor_data',
  title: 'Vendor Information',
  description: 'Marketplace vendor and partner details',
  icon: Store,
  tableName: 'vendors',
  category: 'vendors',
  fields: [
    { name: 'vendor_code', type: 'String', required: true, description: 'Unique vendor identifier', example: 'VND-001', validation: 'Unique, alphanumeric' },
    { name: 'company_name', type: 'String', required: true, description: 'Legal company name', example: 'Fitness First Middle East', validation: 'Max 200 characters' },
    { name: 'company_name_ar', type: 'String', required: false, description: 'Arabic company name', example: 'فتنس فيرست الشرق الأوسط', validation: 'Arabic text' },
    { name: 'trade_license_number', type: 'String', required: true, description: 'Trade license number', example: 'TL-123456', validation: 'Alphanumeric' },
    { name: 'tax_registration_number', type: 'String', required: false, description: 'VAT/Tax registration', example: 'TRN100123456789', validation: 'TRN format' },
    { name: 'category', type: 'String', required: true, description: 'Primary business category', example: 'Fitness & Wellness', validation: 'Predefined categories' },
    { name: 'sub_category', type: 'String', required: false, description: 'Sub-category', example: 'Gym Memberships', validation: 'Predefined sub-categories' },
    { name: 'description', type: 'Text', required: true, description: 'Company description', example: 'Leading fitness chain with 30+ locations across UAE', validation: 'Max 500 chars' },
    { name: 'logo_url', type: 'URL', required: false, description: 'Company logo URL', example: 'https://cdn.fitnessfirst.ae/logo.png', validation: 'Valid URL' },
    { name: 'website_url', type: 'URL', required: false, description: 'Company website', example: 'https://www.fitnessfirst.ae', validation: 'Valid URL' },
    { name: 'contact_name', type: 'String', required: true, description: 'Primary contact name', example: 'Ahmed Hassan', validation: 'Max 100 chars' },
    { name: 'contact_email', type: 'Email', required: true, description: 'Primary contact email', example: 'ahmed@fitnessfirst.ae', validation: 'Valid email' },
    { name: 'contact_phone', type: 'String', required: true, description: 'Contact phone number', example: '+971 4 123 4567', validation: 'International format' },
    { name: 'billing_email', type: 'Email', required: true, description: 'Billing/invoice email', example: 'billing@fitnessfirst.ae', validation: 'Valid email' },
    { name: 'bank_name', type: 'String', required: true, description: 'Bank for settlements', example: 'Emirates NBD', validation: 'Bank name' },
    { name: 'bank_account_iban', type: 'String', required: true, description: 'Bank IBAN', example: 'AE070331234567890123456', validation: 'Valid IBAN' },
    { name: 'commission_rate', type: 'Decimal', required: true, description: 'Platform commission %', example: '10', validation: '0-50' },
    { name: 'settlement_frequency', type: 'Enum', required: true, description: 'Settlement frequency', example: 'Monthly', validation: 'Weekly, Bi-weekly, Monthly' },
    { name: 'contract_start_date', type: 'Date', required: true, description: 'Partnership start date', example: '2024-01-01', validation: 'YYYY-MM-DD' },
    { name: 'contract_end_date', type: 'Date', required: false, description: 'Partnership end date', example: '2025-12-31', validation: 'YYYY-MM-DD' },
    { name: 'is_active', type: 'Boolean', required: true, description: 'Active on marketplace', example: 'true', validation: 'true/false' },
    { name: 'is_featured', type: 'Boolean', required: false, description: 'Featured vendor', example: 'false', validation: 'true/false' },
    { name: 'locations_count', type: 'Integer', required: false, description: 'Number of locations', example: '32', validation: 'Positive integer' },
    { name: 'average_rating', type: 'Decimal', required: false, description: 'Average user rating', example: '4.5', validation: '0-5' },
  ],
  notes: [
    'Trade license must be valid and renewed annually',
    'Commission rates are negotiated per vendor contract',
    'Settlement is processed based on confirmed redemptions',
    'Featured vendors appear prominently in marketplace',
    'Inactive vendors are hidden from employee view',
  ],
};

// Marketplace Offers
export const marketplaceOffersTemplate: TemplateSection = {
  id: 'marketplace_offers',
  title: 'Marketplace Offers',
  description: 'Vendor offers, discounts, and deals for employees',
  icon: ShoppingBag,
  tableName: 'marketplace_offers',
  category: 'marketplace',
  fields: [
    { name: 'offer_code', type: 'String', required: true, description: 'Unique offer identifier', example: 'OFF-FF-001', validation: 'Unique, alphanumeric' },
    { name: 'vendor_code', type: 'String', required: true, description: 'Vendor code', example: 'VND-001', validation: 'Must exist in vendors' },
    { name: 'title', type: 'String', required: true, description: 'Offer title', example: '30% Off Annual Membership', validation: 'Max 100 chars' },
    { name: 'title_ar', type: 'String', required: false, description: 'Arabic title', example: 'خصم 30% على العضوية السنوية', validation: 'Arabic text' },
    { name: 'description', type: 'Text', required: true, description: 'Offer description', example: 'Get 30% off on any annual gym membership package', validation: 'Max 500 chars' },
    { name: 'description_ar', type: 'Text', required: false, description: 'Arabic description', example: 'احصل على خصم 30% على أي باقة عضوية سنوية', validation: 'Arabic text' },
    { name: 'category', type: 'String', required: true, description: 'Offer category', example: 'Fitness', validation: 'Predefined categories' },
    { name: 'discount_type', type: 'Enum', required: true, description: 'Type of discount', example: 'Percentage', validation: 'Percentage, Fixed Amount, Free Item' },
    { name: 'discount_value', type: 'Decimal', required: true, description: 'Discount value', example: '30', validation: 'Positive number' },
    { name: 'original_price', type: 'Decimal', required: false, description: 'Original price before discount', example: '5000.00', validation: 'Positive number' },
    { name: 'discounted_price', type: 'Decimal', required: false, description: 'Price after discount', example: '3500.00', validation: 'Positive number' },
    { name: 'min_purchase_amount', type: 'Decimal', required: false, description: 'Minimum purchase required', example: '500.00', validation: 'Positive number' },
    { name: 'max_discount_amount', type: 'Decimal', required: false, description: 'Maximum discount cap', example: '2000.00', validation: 'Positive number' },
    { name: 'redemption_code', type: 'String', required: false, description: 'Promo code for redemption', example: 'CORP30', validation: 'Alphanumeric' },
    { name: 'redemption_type', type: 'Enum', required: true, description: 'How offer is redeemed', example: 'Code', validation: 'Code, QR, Link, In-Store' },
    { name: 'redemption_instructions', type: 'Text', required: false, description: 'How to redeem', example: 'Show this code at any Fitness First location', validation: 'Max 500 chars' },
    { name: 'valid_from', type: 'Date', required: true, description: 'Offer start date', example: '2024-01-01', validation: 'YYYY-MM-DD' },
    { name: 'valid_until', type: 'Date', required: true, description: 'Offer end date', example: '2024-12-31', validation: 'YYYY-MM-DD' },
    { name: 'usage_limit_total', type: 'Integer', required: false, description: 'Total redemption limit', example: '1000', validation: 'Positive integer' },
    { name: 'usage_limit_per_user', type: 'Integer', required: false, description: 'Limit per employee', example: '1', validation: 'Positive integer' },
    { name: 'terms', type: 'Text', required: false, description: 'Terms and conditions', example: 'Valid for new members only. Cannot be combined with other offers.', validation: 'Max 1000 chars' },
    { name: 'image_url', type: 'URL', required: false, description: 'Offer image URL', example: 'https://cdn.fitnessfirst.ae/offers/annual.jpg', validation: 'Valid URL' },
    { name: 'tags', type: 'Array', required: false, description: 'Search tags (comma-separated)', example: 'fitness, gym, health, wellness', validation: 'Comma-separated' },
    { name: 'is_active', type: 'Boolean', required: true, description: 'Offer is active', example: 'true', validation: 'true/false' },
    { name: 'is_featured', type: 'Boolean', required: false, description: 'Featured on homepage', example: 'false', validation: 'true/false' },
    { name: 'target_grades', type: 'Array', required: false, description: 'Eligible grades (comma-separated)', example: 'G5, G6, G7, G8', validation: 'Comma-separated or empty for all' },
    { name: 'target_departments', type: 'Array', required: false, description: 'Eligible departments', example: 'Technology, Finance', validation: 'Comma-separated or empty for all' },
  ],
  notes: [
    'Offers with usage limits are tracked automatically',
    'Featured offers appear on employee dashboard',
    'Target grades/departments restrict visibility',
    'Expired offers are hidden automatically',
    'Redemption codes should be unique per offer',
  ],
};

// Health Providers
export const healthProvidersTemplate: TemplateSection = {
  id: 'health_providers',
  title: 'Health & Insurance Providers',
  description: 'Network hospitals, clinics, and insurance providers',
  icon: Stethoscope,
  tableName: 'health_providers',
  category: 'reference',
  fields: [
    { name: 'provider_code', type: 'String', required: true, description: 'Unique provider identifier', example: 'HP-001', validation: 'Unique, alphanumeric' },
    { name: 'name', type: 'String', required: true, description: 'Provider name', example: 'American Hospital Dubai', validation: 'Max 200 chars' },
    { name: 'name_ar', type: 'String', required: false, description: 'Arabic name', example: 'المستشفى الأمريكي دبي', validation: 'Arabic text' },
    { name: 'provider_type', type: 'Enum', required: true, description: 'Type of provider', example: 'Hospital', validation: 'Hospital, Clinic, Pharmacy, Lab, Dental, Optical' },
    { name: 'specialty', type: 'String', required: false, description: 'Primary specialty', example: 'Multi-specialty', validation: 'Medical specialty' },
    { name: 'in_network', type: 'Boolean', required: true, description: 'Part of insurance network', example: 'true', validation: 'true/false' },
    { name: 'network_tier', type: 'Enum', required: false, description: 'Network coverage tier', example: 'Premium', validation: 'Basic, Standard, Premium' },
    { name: 'insurance_accepted', type: 'Array', required: false, description: 'Insurance plans accepted', example: 'Daman, AXA, Cigna', validation: 'Comma-separated' },
    { name: 'direct_billing', type: 'Boolean', required: true, description: 'Offers direct billing', example: 'true', validation: 'true/false' },
    { name: 'area', type: 'String', required: true, description: 'Location area', example: 'Dubai Healthcare City', validation: 'Area name' },
    { name: 'address', type: 'Text', required: true, description: 'Full address', example: 'Oud Metha Road, Dubai Healthcare City', validation: 'Max 300 chars' },
    { name: 'latitude', type: 'Decimal', required: false, description: 'GPS latitude', example: '25.2048', validation: 'Valid coordinate' },
    { name: 'longitude', type: 'Decimal', required: false, description: 'GPS longitude', example: '55.2708', validation: 'Valid coordinate' },
    { name: 'phone', type: 'String', required: true, description: 'Contact number', example: '+971 4 336 7777', validation: 'International format' },
    { name: 'emergency_phone', type: 'String', required: false, description: 'Emergency number', example: '+971 4 336 7000', validation: 'International format' },
    { name: 'email', type: 'Email', required: false, description: 'Contact email', example: 'info@ahdubai.com', validation: 'Valid email' },
    { name: 'website', type: 'URL', required: false, description: 'Website URL', example: 'https://www.ahdubai.com', validation: 'Valid URL' },
    { name: 'operating_hours', type: 'String', required: false, description: 'Operating hours', example: '24/7', validation: 'Free text' },
    { name: 'rating', type: 'Decimal', required: false, description: 'Average rating', example: '4.7', validation: '0-5' },
    { name: 'services_offered', type: 'Array', required: false, description: 'Services offered', example: 'Emergency, Surgery, Radiology, Lab', validation: 'Comma-separated' },
    { name: 'languages_spoken', type: 'Array', required: false, description: 'Languages available', example: 'English, Arabic, Hindi, Urdu', validation: 'Comma-separated' },
  ],
  notes: [
    'In-network providers offer direct billing with insurance',
    'Network tier affects co-pay and coverage percentages',
    'GPS coordinates enable map-based provider search',
    'Services list helps employees find specialized care',
    'Rating is based on employee feedback',
  ],
};

// Schools
export const schoolsTemplate: TemplateSection = {
  id: 'schools',
  title: 'Schools & Education',
  description: 'Partner schools for education benefit',
  icon: GraduationCap,
  tableName: 'schools',
  category: 'reference',
  fields: [
    { name: 'school_code', type: 'String', required: true, description: 'Unique school identifier', example: 'SCH-001', validation: 'Unique, alphanumeric' },
    { name: 'name', type: 'String', required: true, description: 'School name', example: 'GEMS Wellington Academy', validation: 'Max 200 chars' },
    { name: 'name_ar', type: 'String', required: false, description: 'Arabic name', example: 'أكاديمية جيمس ولينغتون', validation: 'Arabic text' },
    { name: 'curriculum', type: 'String', required: true, description: 'Curriculum type', example: 'British', validation: 'British, American, IB, Indian, French, etc.' },
    { name: 'grade_range', type: 'String', required: true, description: 'Grades offered', example: 'FS1-Year 13', validation: 'Grade range format' },
    { name: 'location', type: 'String', required: true, description: 'Location/Area', example: 'Al Khail Road, Dubai', validation: 'Area name' },
    { name: 'address', type: 'Text', required: true, description: 'Full address', example: 'Al Khail Road, Near Mall of Emirates, Dubai', validation: 'Max 300 chars' },
    { name: 'annual_fee_min', type: 'Decimal', required: true, description: 'Minimum annual fee', example: '45000.00', validation: 'Positive number' },
    { name: 'annual_fee_max', type: 'Decimal', required: true, description: 'Maximum annual fee', example: '95000.00', validation: 'Positive number' },
    { name: 'registration_fee', type: 'Decimal', required: false, description: 'One-time registration fee', example: '5000.00', validation: 'Positive number' },
    { name: 'is_partner', type: 'Boolean', required: true, description: 'Corporate partner school', example: 'true', validation: 'true/false' },
    { name: 'corporate_discount_percent', type: 'Decimal', required: false, description: 'Corporate discount %', example: '10', validation: '0-50' },
    { name: 'khda_rating', type: 'Enum', required: false, description: 'KHDA rating', example: 'Outstanding', validation: 'Outstanding, Very Good, Good, Acceptable' },
    { name: 'rating', type: 'Decimal', required: false, description: 'Parent rating', example: '4.5', validation: '0-5' },
    { name: 'facilities', type: 'Array', required: false, description: 'Available facilities', example: 'Swimming Pool, Library, Science Labs, Sports Complex', validation: 'Comma-separated' },
    { name: 'extracurricular', type: 'Array', required: false, description: 'Extra activities offered', example: 'Football, Swimming, Drama, Music, Robotics', validation: 'Comma-separated' },
    { name: 'phone', type: 'String', required: true, description: 'Contact number', example: '+971 4 427 2000', validation: 'International format' },
    { name: 'email', type: 'Email', required: false, description: 'Admissions email', example: 'admissions@gemswellington.com', validation: 'Valid email' },
    { name: 'website_url', type: 'URL', required: false, description: 'School website', example: 'https://www.gemswellington.com', validation: 'Valid URL' },
    { name: 'application_deadline', type: 'String', required: false, description: 'Application deadline', example: 'March 31', validation: 'Month Day format' },
    { name: 'transport_available', type: 'Boolean', required: false, description: 'School transport available', example: 'true', validation: 'true/false' },
    { name: 'transport_fee_annual', type: 'Decimal', required: false, description: 'Annual transport fee', example: '8000.00', validation: 'Positive number' },
  ],
  notes: [
    'Partner schools offer corporate discounts',
    'KHDA ratings are updated annually',
    'Fee ranges vary by grade level',
    'Transport availability depends on route coverage',
    'Application deadlines vary by school year',
  ],
};

// Housing Areas
export const housingAreasTemplate: TemplateSection = {
  id: 'housing_areas',
  title: 'Housing Areas & Rentals',
  description: 'Reference data for housing allowance and accommodation',
  icon: Home,
  tableName: 'housing_areas',
  category: 'reference',
  fields: [
    { name: 'area_code', type: 'String', required: true, description: 'Unique area identifier', example: 'AREA-001', validation: 'Unique, alphanumeric' },
    { name: 'name', type: 'String', required: true, description: 'Area name', example: 'Dubai Marina', validation: 'Max 100 chars' },
    { name: 'name_ar', type: 'String', required: false, description: 'Arabic name', example: 'دبي مارينا', validation: 'Arabic text' },
    { name: 'city', type: 'String', required: true, description: 'City', example: 'Dubai', validation: 'City name' },
    { name: 'avg_rent_studio', type: 'Decimal', required: false, description: 'Avg studio rent (annual)', example: '45000.00', validation: 'Positive number' },
    { name: 'avg_rent_1br', type: 'Decimal', required: false, description: 'Avg 1BR rent (annual)', example: '65000.00', validation: 'Positive number' },
    { name: 'avg_rent_2br', type: 'Decimal', required: false, description: 'Avg 2BR rent (annual)', example: '95000.00', validation: 'Positive number' },
    { name: 'avg_rent_3br', type: 'Decimal', required: false, description: 'Avg 3BR rent (annual)', example: '140000.00', validation: 'Positive number' },
    { name: 'avg_rent_4br', type: 'Decimal', required: false, description: 'Avg 4BR rent (annual)', example: '200000.00', validation: 'Positive number' },
    { name: 'avg_rent_villa', type: 'Decimal', required: false, description: 'Avg villa rent (annual)', example: '250000.00', validation: 'Positive number' },
    { name: 'commute_to_difc_mins', type: 'Integer', required: false, description: 'Commute to DIFC (minutes)', example: '15', validation: 'Positive integer' },
    { name: 'commute_to_downtown_mins', type: 'Integer', required: false, description: 'Commute to Downtown (minutes)', example: '10', validation: 'Positive integer' },
    { name: 'metro_accessible', type: 'Boolean', required: false, description: 'Near metro station', example: 'true', validation: 'true/false' },
    { name: 'family_friendly', type: 'Boolean', required: false, description: 'Family-friendly area', example: 'true', validation: 'true/false' },
    { name: 'lifestyle_rating', type: 'Enum', required: false, description: 'Lifestyle category', example: 'Premium', validation: 'Budget, Mid-range, Premium, Luxury' },
    { name: 'amenities_nearby', type: 'Array', required: false, description: 'Nearby amenities', example: 'Malls, Restaurants, Beach, Schools, Hospitals', validation: 'Comma-separated' },
    { name: 'description', type: 'Text', required: false, description: 'Area description', example: 'Vibrant waterfront community with modern high-rises', validation: 'Max 500 chars' },
  ],
  notes: [
    'Rental data should be updated quarterly from market sources',
    'Commute times based on typical traffic conditions',
    'Metro accessibility affects transport allowance recommendations',
    'Family-friendly rating considers schools and parks proximity',
  ],
};

// Grade Structure
export const gradeStructureTemplate: TemplateSection = {
  id: 'grade_structure',
  title: 'Grade & Band Structure',
  description: 'Employee grade levels and associated benefit tiers',
  icon: Award,
  tableName: 'custom:grade_structure',
  category: 'organization',
  fields: [
    { name: 'grade_code', type: 'String', required: true, description: 'Grade identifier', example: 'G7', validation: 'Unique, alphanumeric' },
    { name: 'grade_name', type: 'String', required: true, description: 'Grade display name', example: 'Senior Manager', validation: 'Max 100 chars' },
    { name: 'grade_level', type: 'Integer', required: true, description: 'Numeric level (for ordering)', example: '7', validation: 'Positive integer' },
    { name: 'band', type: 'String', required: false, description: 'Salary band', example: 'Band C', validation: 'Band identifier' },
    { name: 'salary_range_min', type: 'Decimal', required: true, description: 'Min monthly salary', example: '25000.00', validation: 'Positive number' },
    { name: 'salary_range_max', type: 'Decimal', required: true, description: 'Max monthly salary', example: '40000.00', validation: 'Positive number' },
    { name: 'housing_allowance_annual', type: 'Decimal', required: true, description: 'Annual housing allowance', example: '120000.00', validation: 'Positive number' },
    { name: 'transport_allowance_monthly', type: 'Decimal', required: true, description: 'Monthly transport allowance', example: '2500.00', validation: 'Positive number' },
    { name: 'education_allowance_per_child', type: 'Decimal', required: false, description: 'Education allowance per child', example: '50000.00', validation: 'Positive number' },
    { name: 'max_children_education', type: 'Integer', required: false, description: 'Max children for education benefit', example: '3', validation: 'Positive integer' },
    { name: 'annual_leave_days', type: 'Integer', required: true, description: 'Annual leave entitlement', example: '30', validation: 'Positive integer' },
    { name: 'health_insurance_tier', type: 'String', required: true, description: 'Health insurance tier', example: 'Gold', validation: 'Bronze, Silver, Gold, Platinum' },
    { name: 'life_insurance_multiplier', type: 'Decimal', required: false, description: 'Life insurance (x annual salary)', example: '3', validation: 'Positive number' },
    { name: 'bonus_target_percent', type: 'Decimal', required: false, description: 'Target bonus %', example: '20', validation: '0-200' },
    { name: 'equity_eligible', type: 'Boolean', required: false, description: 'Eligible for equity grants', example: 'true', validation: 'true/false' },
    { name: 'flight_class', type: 'Enum', required: false, description: 'Business travel flight class', example: 'Business', validation: 'Economy, Premium Economy, Business, First' },
    { name: 'car_allowance_eligible', type: 'Boolean', required: false, description: 'Eligible for car allowance', example: 'true', validation: 'true/false' },
    { name: 'car_allowance_monthly', type: 'Decimal', required: false, description: 'Monthly car allowance', example: '3000.00', validation: 'Positive number' },
  ],
  notes: [
    'Grade structure defines benefit tiers across the organization',
    'Salary ranges are guidelines and may vary by role/location',
    'Insurance tiers affect coverage levels and network access',
    'Flight class applies to business travel bookings',
    'Equity eligibility typically starts at senior levels',
  ],
};

// All templates organized by category
export const allTemplates: TemplateSection[] = [
  organizationSetupTemplate,
  gradeStructureTemplate,
  employeeDataTemplate,
  employmentDataTemplate,
  salaryDataTemplate,
  dependentsDataTemplate,
  benefitsPolicyTemplate,
  benefitEntitlementTemplate,
  leaveBalanceTemplate,
  vendorDataTemplate,
  marketplaceOffersTemplate,
  healthProvidersTemplate,
  schoolsTemplate,
  housingAreasTemplate,
];

export const templateCategories = {
  organization: { label: 'Organization', templates: ['organization_setup', 'grade_structure'] },
  employees: { label: 'Employees', templates: ['employee_data', 'employment_data', 'dependents_data'] },
  compensation: { label: 'Compensation', templates: ['salary_data'] },
  benefits: { label: 'Benefits Policy', templates: ['benefits_policy', 'benefit_entitlement'] },
  leave: { label: 'Leave & Time Off', templates: ['leave_balance'] },
  vendors: { label: 'Vendors', templates: ['vendor_data'] },
  marketplace: { label: 'Marketplace', templates: ['marketplace_offers'] },
  reference: { label: 'Reference Data', templates: ['health_providers', 'schools', 'housing_areas'] },
};
