import { CalendarEvent, ChecklistStep, EventOwner } from './types';
import { addDays, subDays } from 'date-fns';

const owners: Record<string, EventOwner> = {
  sarah: { id: '1', name: 'Sarah Ahmed', role: 'HR Manager' },
  mohammed: { id: '2', name: 'Mohammed Al-Rashid', role: 'Finance Lead' },
  fatima: { id: '3', name: 'Fatima Hassan', role: 'Benefits Admin' },
  omar: { id: '4', name: 'Omar Khalil', role: 'Procurement' },
};

const payrollChecklist: ChecklistStep[] = [
  {
    id: 'pc-1',
    title: 'Review pending claims for payroll inclusion',
    responsible: owners.fatima,
    status: 'completed',
    dueDate: subDays(new Date(), 2),
  },
  {
    id: 'pc-2',
    title: 'Approve high-value claims (>AED 5,000)',
    responsible: owners.sarah,
    status: 'in_progress',
    dueDate: new Date(),
  },
  {
    id: 'pc-3',
    title: 'Generate settlement batch for approved claims',
    responsible: owners.fatima,
    status: 'pending',
    dueDate: addDays(new Date(), 1),
  },
  {
    id: 'pc-4',
    title: 'Export payroll file to Finance',
    responsible: owners.mohammed,
    status: 'pending',
    dueDate: addDays(new Date(), 2),
  },
  {
    id: 'pc-5',
    title: 'Confirm bank transfer initiated',
    responsible: owners.mohammed,
    status: 'pending',
    dueDate: addDays(new Date(), 3),
  },
];

const enrollmentChecklist: ChecklistStep[] = [
  {
    id: 'oe-1',
    title: 'Send enrollment reminder to all employees',
    responsible: owners.sarah,
    status: 'completed',
  },
  {
    id: 'oe-2',
    title: 'Review new benefit selections',
    responsible: owners.fatima,
    status: 'in_progress',
  },
  {
    id: 'oe-3',
    title: 'Process dependent additions',
    responsible: owners.fatima,
    status: 'pending',
  },
  {
    id: 'oe-4',
    title: 'Update insurance provider portal',
    responsible: owners.sarah,
    status: 'blocked',
    notes: 'Waiting for provider API access',
  },
];

export const mockCalendarEvents: CalendarEvent[] = [
  {
    id: 'evt-1',
    title: 'January Payroll Cutoff',
    description: 'Process all approved claims for January payroll cycle',
    type: 'payroll_cutoff',
    date: addDays(new Date(), 3),
    status: 'upcoming',
    owner: owners.sarah,
    linkedAction: {
      id: 'act-1',
      title: 'Process 28 pending claims',
      route: '/employer/ops',
      status: 'in_progress',
    },
    checklist: payrollChecklist,
    recurrence: 'monthly',
    priority: 'critical',
  },
  {
    id: 'evt-2',
    title: 'Health Insurance Policy Renewal',
    description: 'Annual renewal with Emirates Insurance Co.',
    type: 'policy_renewal',
    date: addDays(new Date(), 19),
    status: 'upcoming',
    owner: owners.sarah,
    linkedAction: {
      id: 'act-2',
      title: 'Review renewal terms',
      route: '/employer/policies',
      status: 'pending',
    },
    recurrence: 'annually',
    priority: 'high',
  },
  {
    id: 'evt-3',
    title: 'Q1 Settlement Export',
    description: 'Export all Q1 settlements for audit',
    type: 'settlement_export',
    date: addDays(new Date(), 45),
    status: 'upcoming',
    owner: owners.mohammed,
    linkedAction: {
      id: 'act-3',
      title: 'Prepare Q1 report',
      route: '/employer/settlements',
      status: 'pending',
    },
    recurrence: 'quarterly',
    priority: 'medium',
  },
  {
    id: 'evt-4',
    title: 'Annual Benefits Open Enrollment',
    description: 'Employees can modify benefit selections',
    type: 'open_enrollment',
    date: addDays(new Date(), 7),
    status: 'upcoming',
    owner: owners.fatima,
    linkedAction: {
      id: 'act-4',
      title: 'Launch enrollment portal',
      route: '/employer/communications',
      status: 'in_progress',
    },
    checklist: enrollmentChecklist,
    recurrence: 'annually',
    priority: 'high',
  },
  {
    id: 'evt-5',
    title: 'Gym Partnership Renewal',
    description: 'Fitness First corporate partnership expires',
    type: 'vendor_contract',
    date: addDays(new Date(), 30),
    status: 'upcoming',
    owner: owners.omar,
    linkedAction: {
      id: 'act-5',
      title: 'Negotiate renewal terms',
      route: '/employer/integrations',
      status: 'pending',
    },
    recurrence: 'annually',
    priority: 'medium',
  },
  {
    id: 'evt-6',
    title: 'Education Allowance Claims Deadline',
    description: 'Last day to submit education reimbursement claims',
    type: 'payroll_cutoff',
    date: addDays(new Date(), 60),
    status: 'upcoming',
    owner: owners.fatima,
    recurrence: 'annually',
    priority: 'high',
  },
  {
    id: 'evt-7',
    title: 'December Payroll Completed',
    description: 'All December claims processed and paid',
    type: 'payroll_cutoff',
    date: subDays(new Date(), 5),
    status: 'completed',
    owner: owners.sarah,
    recurrence: 'monthly',
    priority: 'critical',
  },
];
